"""Stream type classes for tap-currencyfreaks."""

from singer_sdk import typing as th  # JSON Schema typing helpers

from tap_currencyfreaks.client import CurrencyFreaksStream


class LatestStream(CurrencyFreaksStream):
    """Define custom stream."""
    name = "latest"
    path = "/latest"
    primary_keys = ["id"]
    replication_key = None
    # Optionally, you may also use `schema_filepath` in place of `schema`:
    # schema_filepath = SCHEMAS_DIR / "users.json"
    schema = th.PropertiesList(
        th.Property(
            "id",
            th.StringType,
            description="The timestamp of this entry"
        ),
        th.Property(
            "base",
            th.StringType,
            description="The base currency"
        ),
        th.Property(
            "date",
            th.DateTimeType(),
            description="The time of these rates"
        ),
        th.Property(
            "rates",
            th.PropertiesList(
                th.Property("FJD", th.NumberType),
                th.Property("MATIC", th.NumberType),
                th.Property("MXN", th.NumberType),
                th.Property("STD", th.NumberType),
                th.Property("SCR", th.NumberType),
                th.Property("CDF", th.NumberType),
                th.Property("BBD", th.NumberType),
                th.Property("HNL", th.NumberType),
                th.Property("UGX", th.NumberType),
                th.Property("ZAR", th.NumberType),
                th.Property("STN", th.NumberType),
                th.Property("CUC", th.NumberType),
                th.Property("BSD", th.NumberType),
                th.Property("SDG", th.NumberType),
                th.Property("IQD", th.NumberType),
                th.Property("CUP", th.NumberType),
                th.Property("GMD", th.NumberType),
                th.Property("TWD", th.NumberType),
                th.Property("ZRX", th.NumberType),
                th.Property("RSD", th.NumberType),
                th.Property("BSV", th.NumberType),
                th.Property("BCH", th.NumberType),
                th.Property("MYR", th.NumberType),
                th.Property("OMG", th.NumberType),
                th.Property("FKP", th.NumberType),
                th.Property("BAND", th.NumberType),
                th.Property("XOF", th.NumberType),
                th.Property("BTC", th.NumberType),
                th.Property("UYU", th.NumberType),
                th.Property("CVC", th.NumberType),
                th.Property("CVE", th.NumberType),
                th.Property("OMR", th.NumberType),
                th.Property("KES", th.NumberType),
                th.Property("SEK", th.NumberType),
                th.Property("BTN", th.NumberType),
                th.Property("GNF", th.NumberType),
                th.Property("MZN", th.NumberType),
                th.Property("SVC", th.NumberType),
                th.Property("ARS", th.NumberType),
                th.Property("QAR", th.NumberType),
                th.Property("IRR", th.NumberType),
                th.Property("ANKR", th.NumberType),
                th.Property("SUSHI", th.NumberType),
                th.Property("XPD", th.NumberType),
                th.Property("ALGO", th.NumberType),
                th.Property("THB", th.NumberType),
                th.Property("UZS", th.NumberType),
                th.Property("XPF", th.NumberType),
                th.Property("WBTC", th.NumberType),
                th.Property("BDT", th.NumberType),
                th.Property("LYD", th.NumberType),
                th.Property("KWD", th.NumberType),
                th.Property("XPT", th.NumberType),
                th.Property("RUB", th.NumberType),
                th.Property("ISK", th.NumberType),
                th.Property("MANA", th.NumberType),
                th.Property("MKD", th.NumberType),
                th.Property("DZD", th.NumberType),
                th.Property("PAB", th.NumberType),
                th.Property("SGD", th.NumberType),
                th.Property("NMR", th.NumberType),
                th.Property("JEP", th.NumberType),
                th.Property("MKR", th.NumberType),
                th.Property("KGS", th.NumberType),
                th.Property("ZEC", th.NumberType),
                th.Property("REN", th.NumberType),
                th.Property("REP", th.NumberType),
                th.Property("XAF", th.NumberType),
                th.Property("ADA", th.NumberType),
                th.Property("XAG", th.NumberType),
                th.Property("STORJ", th.NumberType),
                th.Property("CHF", th.NumberType),
                th.Property("HRK", th.NumberType),
                th.Property("DJF", th.NumberType),
                th.Property("PAX", th.NumberType),
                th.Property("DOGE", th.NumberType),
                th.Property("TZS", th.NumberType),
                th.Property("VND", th.NumberType),
                th.Property("XAU", th.NumberType),
                th.Property("AUD", th.NumberType),
                th.Property("KHR", th.NumberType),
                th.Property("IDR", th.NumberType),
                th.Property("KYD", th.NumberType),
                th.Property("XRP", th.NumberType),
                th.Property("BWP", th.NumberType),
                th.Property("SHP", th.NumberType),
                th.Property("TJS", th.NumberType),
                th.Property("AED", th.NumberType),
                th.Property("RWF", th.NumberType),
                th.Property("DKK", th.NumberType),
                th.Property("BGN", th.NumberType),
                th.Property("UMA", th.NumberType),
                th.Property("MMK", th.NumberType),
                th.Property("NOK", th.NumberType),
                th.Property("SYP", th.NumberType),
                th.Property("ZWL", th.NumberType),
                th.Property("LKR", th.NumberType),
                th.Property("CZK", th.NumberType),
                th.Property("XCD", th.NumberType),
                th.Property("HTG", th.NumberType),
                th.Property("BHD", th.NumberType),
                th.Property("CGLD", th.NumberType),
                th.Property("KZT", th.NumberType),
                th.Property("SZL", th.NumberType),
                th.Property("YER", th.NumberType),
                th.Property("GRT", th.NumberType),
                th.Property("AFN", th.NumberType),
                th.Property("AWG", th.NumberType),
                th.Property("NPR", th.NumberType),
                th.Property("UNI", th.NumberType),
                th.Property("AAVE", th.NumberType),
                th.Property("MNT", th.NumberType),
                th.Property("GBP", th.NumberType),
                th.Property("BYN", th.NumberType),
                th.Property("HUF", th.NumberType),
                th.Property("BYR", th.NumberType),
                th.Property("GBX", th.NumberType),
                th.Property("YFI", th.NumberType),
                th.Property("BIF", th.NumberType),
                th.Property("XTZ", th.NumberType),
                th.Property("XDR", th.NumberType),
                th.Property("EOS", th.NumberType),
                th.Property("BZD", th.NumberType),
                th.Property("MOP", th.NumberType),
                th.Property("NAD", th.NumberType),
                th.Property("SKL", th.NumberType),
                th.Property("PEN", th.NumberType),
                th.Property("WST", th.NumberType),
                th.Property("TMT", th.NumberType),
                th.Property("CLF", th.NumberType),
                th.Property("GTQ", th.NumberType),
                th.Property("CLP", th.NumberType),
                th.Property("DNT", th.NumberType),
                th.Property("TND", th.NumberType),
                th.Property("COMP", th.NumberType),
                th.Property("SLL", th.NumberType),
                th.Property("DOP", th.NumberType),
                th.Property("KMF", th.NumberType),
                th.Property("GEL", th.NumberType),
                th.Property("MAD", th.NumberType),
                th.Property("TOP", th.NumberType),
                th.Property("AZN", th.NumberType),
                th.Property("PGK", th.NumberType),
                th.Property("CNH", th.NumberType),
                th.Property("UAH", th.NumberType),
                th.Property("ERN", th.NumberType),
                th.Property("KNC", th.NumberType),
                th.Property("MRO", th.NumberType),
                th.Property("CNY", th.NumberType),
                th.Property("ATOM", th.NumberType),
                th.Property("MRU", th.NumberType),
                th.Property("BMD", th.NumberType),
                th.Property("PHP", th.NumberType),
                th.Property("SNX", th.NumberType),
                th.Property("PYG", th.NumberType),
                th.Property("JMD", th.NumberType),
                th.Property("COP", th.NumberType),
                th.Property("USD", th.NumberType),
                th.Property("DAI", th.NumberType),
                th.Property("GGP", th.NumberType),
                th.Property("ETB", th.NumberType),
                th.Property("ETC", th.NumberType),
                th.Property("SOS", th.NumberType),
                th.Property("VEF", th.NumberType),
                th.Property("VUV", th.NumberType),
                th.Property("LAK", th.NumberType),
                th.Property("ETH", th.NumberType),
                th.Property("BND", th.NumberType),
                th.Property("LRC", th.NumberType),
                th.Property("LRD", th.NumberType),
                th.Property("ALL", th.NumberType),
                th.Property("VES", th.NumberType),
                th.Property("ZMW", th.NumberType),
                th.Property("BNT", th.NumberType),
                th.Property("OXT", th.NumberType),
                th.Property("DASH", th.NumberType),
                th.Property("ILS", th.NumberType),
                th.Property("GHS", th.NumberType),
                th.Property("GYD", th.NumberType),
                th.Property("KPW", th.NumberType),
                th.Property("BOB", th.NumberType),
                th.Property("MDL", th.NumberType),
                th.Property("AMD", th.NumberType),
                th.Property("TRY", th.NumberType),
                th.Property("LBP", th.NumberType),
                th.Property("JOD", th.NumberType),
                th.Property("GUSD", th.NumberType),
                th.Property("HKD", th.NumberType),
                th.Property("EUR", th.NumberType),
                th.Property("LSL", th.NumberType),
                th.Property("CAD", th.NumberType),
                th.Property("MUR", th.NumberType),
                th.Property("IMP", th.NumberType),
                th.Property("GIP", th.NumberType),
                th.Property("RON", th.NumberType),
                th.Property("NGN", th.NumberType),
                th.Property("CRC", th.NumberType),
                th.Property("PKR", th.NumberType),
                th.Property("ANG", th.NumberType),
                th.Property("LTC", th.NumberType),
                th.Property("USDC", th.NumberType),
                th.Property("SRD", th.NumberType),
                th.Property("SAR", th.NumberType),
                th.Property("TTD", th.NumberType),
                th.Property("CRV", th.NumberType),
                th.Property("NU", th.NumberType),
                th.Property("MVR", th.NumberType),
                th.Property("INR", th.NumberType),
                th.Property("KRW", th.NumberType),
                th.Property("JPY", th.NumberType),
                th.Property("AOA", th.NumberType),
                th.Property("PLN", th.NumberType),
                th.Property("SBD", th.NumberType),
                th.Property("XLM", th.NumberType),
                th.Property("LINK", th.NumberType),
                th.Property("MWK", th.NumberType),
                th.Property("MGA", th.NumberType),
                th.Property("FIL", th.NumberType),
                th.Property("BAL", th.NumberType),
                th.Property("BAM", th.NumberType),
                th.Property("EGP", th.NumberType),
                th.Property("SSP", th.NumberType),
                th.Property("BAT", th.NumberType),
                th.Property("NIO", th.NumberType),
                th.Property("NZD", th.NumberType),
                th.Property("ETH2", th.NumberType),
                th.Property("BUSD", th.NumberType),
                th.Property("BRL", th.NumberType),
            ),
            description="The rates compared to base currency"
        )
    ).to_dict()
